//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BikeDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductReview
    {
        public int Id { get; set; }
        public string email { get; set; }
        public Nullable<int> rating { get; set; }
        public string comment { get; set; }
        public int productID { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
